/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.paradiddle.messaging;

public interface Mailbox {
    void receive(Object message);
    void retrieve(MessagePattern... patterns);
}
